apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: ciss
spec:
  selector:
    matchLabels:
      app: ciss
      version: v1
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: ciss
        version: v1
        tier: frontend
    spec:
      containers:
        - name: ciss
          image: iameprel/ciss:0.0.9
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
              # name must match the volume name below
              - name: secret-volume
                mountPath: /run/secrets
                readOnly: true
          ports:
            - containerPort: 3000
      # The secret data is exposed to Containers in the Pod through a Volume.
      volumes:
        - name: secret-volume
          secret:
            secretName: my-secret